name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libgcrypt20-dev libgnutls28-dev

      - name: Run test
        run: |
          make test
